version: '3.8'

services:
  pm-agent:
    build: .
    container_name: pm-agent
    environment:
      - API_BASE_URL=http://host.docker.internal:8000
      - PM_AGENT_NAME=PM Agent Alpha
      - HEARTBEAT_INTERVAL=60
      - ISSUE_CHECK_INTERVAL=300
    networks:
      - default
    restart: unless-stopped
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
    # Optional: Mount a log volume for persistent logs
    volumes:
      - pm_agent_logs:/app/logs

  pm-agent-test:
    build: .
    container_name: pm-agent-test
    command: python test_agent.py
    environment:
      - API_BASE_URL=http://host.docker.internal:8000
    networks:
      - default
    # Resource limits for test
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    volumes:
      - pm_agent_logs:/app/logs

networks:
  default:
    external: true
    name: ai-dev_default

volumes:
  pm_agent_logs: 