apiVersion: v1
kind: Service
metadata:
  name: agentic-agile-api-service
  labels:
    app: agentic-agile-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: agentic-agile-api
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: agentic-agile-api-internal
  labels:
    app: agentic-agile-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: agentic-agile-api 