apiVersion: v1
kind: ConfigMap
metadata:
  name: agentic-agile-api-config
  labels:
    app: agentic-agile-api
data:
  # Application configuration
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  API_VERSION: "v1"
  
  # Database configuration (non-sensitive)
  DATABASE_NAME: "agentic_agile"
  MONGODB_DATABASE: "agentic_agile"
  
  # Application settings
  MAX_CONNECTIONS: "100"
  REQUEST_TIMEOUT: "30"
  CORS_ORIGINS: "*"
  
  # Feature flags
  ENABLE_SWAGGER: "true"
  ENABLE_METRICS: "true"
  ENABLE_AUDIT_LOGS: "true" 