apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: agentic-agile-system

resources:
  # API Hub
  - api-hub-deployment.yaml
  - api-hub-service.yaml
  - api-hub-configmap.yaml
  - api-hub-secrets.yaml
  
  # PM Agent
  - pm-agent-deployment.yaml
  - pm-agent-configmap.yaml

namespace: agentic-agile

commonLabels:
  app.kubernetes.io/name: agentic-agile
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/part-of: agentic-agile-system

configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - REGION=us-west-2

secretGenerator:
  - name: api-secrets
    behavior: merge
    literals:
      - ENVIRONMENT=production 