apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-agent-config
  labels:
    app: pm-agent
    agent-type: project-manager
data:
  # Agent configuration
  PM_AGENT_NAME: "PM Agent Alpha"
  AGENT_TYPE: "project_manager"
  VERSION: "1.0.0"
  
  # Behavior settings
  HEARTBEAT_INTERVAL: "60"
  ISSUE_CHECK_INTERVAL: "300"
  MAX_ISSUES_PER_BATCH: "10"
  
  # Triage rules - Priority keywords
  PRIORITY_CRITICAL: "urgent,blocker,production,security,hotfix"
  PRIORITY_HIGH: "important,deadline,customer,feature"
  PRIORITY_MEDIUM: "enhancement,improvement,nice-to-have"
  PRIORITY_LOW: "documentation,cleanup,refactor"
  
  # Triage rules - Issue type detection
  ISSUE_TYPE_BUG: "bug,error,crash,broken,fails"
  ISSUE_TYPE_FEATURE: "feature,new,add,implement"
  ISSUE_TYPE_STORY: "story,user story,as a user"
  ISSUE_TYPE_EPIC: "epic,large,major"
  ISSUE_TYPE_TASK: "task,work,do"
  
  # Assignment rules
  ASSIGN_BUG: "qa_engineer"
  ASSIGN_FEATURE: "product_owner"
  ASSIGN_STORY: "product_owner"
  ASSIGN_TASK: "developer"
  ASSIGN_EPIC: "product_owner"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json" 