version: '3.8'

services:
  qa-agent:
    build: .
    container_name: qa-agent
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - API_HUB_URL=${API_HUB_URL:-http://localhost:8000}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_PASSWORD=${JIRA_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./test_data:/app/test_data
    ports:
      - "8003:8003"
    restart: unless-stopped
    depends_on:
      - api-hub
    networks:
      - agentic-agile-network

  api-hub:
    image: agentic-agile-api:latest
    container_name: api-hub
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - agentic-agile-network

networks:
  agentic-agile-network:
    driver: bridge 